# Fancy Indexing

In [18]:
import numpy as np

In [19]:
arr1 = np.random.randint(0,100,size=10)
arr1 # 1D

array([25,  6, 92, 35, 35, 89, 72, 65, 89, 31])

### Using Fancy indexing to create a sub-ndarray

In [20]:
# indexing the element with index = 0 (i.e. first item)
arr1[0]

25

In [21]:
print(arr1[0], arr1[3], arr1[5])

25 35 89


In [22]:
# we could pick 3 items by index, and wrap it in an Python list
arr1_035 = np.array([arr1[0], arr1[3], arr1[5]])
arr1_035

array([25, 35, 89])

In [23]:
# using fancy indexing, we can achieve this in a fancy way
arr1_037 = arr1[[0, 3, 7]]
arr1_037

array([25, 35, 65])

In [24]:
# shape of arr_037
arr1_037.shape

(3,)

In [25]:
# we could also use fancy indexing to create another n x m ndarray
arr1_0357 = arr1[
  [[0, 3],
   [5, 7]]
]
arr1_0357


array([[25, 35],
       [89, 65]])

In [26]:
# shape of arr_0357
arr1_0357.shape

(2, 2)

In [30]:
# Case
arr2 = np.arange(12).reshape((3,4))
arr2 # 2D


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
# indexing '2' in arr2
arr2[0,2]

2

In [35]:
arr2[1,1]

5

In [36]:
arr2[2,3]

11

In [37]:
arr2_extracts_v1 = arr2[[0,1,2], [2,1,3]] # such fancy indexing operates bit differently when indexing 2D array
arr2_extracts_v1

array([ 2,  5, 11])

In [38]:
row = [0,1,2]
col = [2,1,3]
arr2_extracts_v1 = arr2[row, col] # indexing [0,2] = 2, [1,1] = 5, [2,3] = 11
arr2_extracts_v1

array([ 2,  5, 11])