# NumPy Basics

## Why Do we need NumPy?

In [5]:
nums = [1,2,3,4,5] # 1D Array (Matrix)
print(type(nums)) # type of nums
print(type(nums[0])) # type of elements in nums

<class 'list'>
<class 'int'>


Suppose you want to create a 2D matrix...

In [7]:
nums2D = [[1,2,3],[4,5,6]]
print(nums2D[0][0]) # 1
print(nums2D[0][1]) # 2
print(nums2D[0][2]) # 3
print(nums2D[1][0]) # 4
print(nums2D[1][1]) # 5
print(nums2D[1][2]) # 6

1
2
3
4
5
6


### We use NumPy to:
1. Create n-Dimensinoal Arrays (Matrices)

## 2. Getting Started with NumPy

In [14]:
# install numpy module to device
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np # import numpy module, and give alias called "np"

### 2.1 Creating Numpy Array

There are numerous Ways to Create NumPy Arrays

In [48]:
print("1.", np.array([1,4,2,5,3])) # numpy array with 5 integers in it.

print("2.", np.array([1,2,3,4], dtype="float")) # 1,2,3,4 will be upcasted to "dtype" if possible

"""
1. There are three numbers "i" can be => 2, 4, 6
2. range(i, i+3) will result in range of list with 3 numbers,
    - suppose, i = 2, range(2, 2+3) = [2,3,4]
    - suppose, i = 4, range(4, 4+3) = [4,5,6]
    - suppose, i = 6, range(6, 6+3) = [6,7,8]
"""
print("3.\n", np.array([range(i, i+3) for i in [2,4,6]]))

print("4. NumPy Array full of 0s\n", np.zeros(10, dtype="int"))

print("5. NumPy Array full of 0s\n", np.zeros([5,10], dtype="int"))

1. [1 4 2 5 3]
2. [1. 2. 3. 4.]
3.
 [[2 3 4]
 [4 5 6]
 [6 7 8]]
4. NumPy Array full of 0s
 [0 0 0 0 0 0 0 0 0 0]
5. NumPy Array full of 0s
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [49]:
print("6.NumPy Array Full of 1s\n", np.ones(10, dtype="int"))

print("7.NumPy Array Full of 1s\n", np.ones([5,10], dtype="int"))

print("8. NumPy Array Full of certain number\n", np.full([3,5], 3.14))

print("9. NumPy Arange function\n", np.arange(0, 20))
print(np.arange(0, 20, 2)) # np.arange(start, stop, step), very similar to range(start, stop, step)
print(np.arange(0, 20, 4))
print(np.arange(0, 20, 10))

print("10. NumPy Array with Line spaced\n", np.linspace(0,1,5))

print("11. NumPy Array with Random Integers\n", np.random.randint(0,10, [3,3]))
print("12. NumPy Array with Random Numbers between 0-1\n", np.random.random([3,3]))

6.NumPy Array Full of 1s
 [1 1 1 1 1 1 1 1 1 1]
7.NumPy Array Full of 1s
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
8. NumPy Array Full of certain number
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
9. NumPy Arange function
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  4  8 12 16]
[ 0 10]
10. NumPy Array with Line spaced
 [0.   0.25 0.5  0.75 1.  ]
11. NumPy Array with Random Integers
 [[5 3 1]
 [0 9 9]
 [1 7 0]]
12. NumPy Array with Random Numbers between 0-1
 [[0.34468466 0.31347464 0.76076003]
 [0.63474149 0.4030371  0.56218233]
 [0.68610289 0.26893914 0.79933226]]


## 2.2 NumPy Array vs. Python List

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will **Upcast** if possible.

In [22]:
print([1,2,3,4,3.14])
print(np.array([1,2,3,4,3.14])) # 1, 2, 3, 4 => 1.0, 2.0, 3.0, 4.0 (Upcasting Integer to Float)

[1, 2, 3, 4, 3.14]
[1.   2.   3.   4.   3.14]


## 2.3 NumPy Array Attributes

In [54]:
np_arr = np.full([3,5], 7.5)
print("number of dimensions:", np_arr.ndim)
print("data type in array:", np_arr.dtype)
print("numpy array shapre(n x m?):", np_arr.shape)
print("size in bytes:", np_arr.size)

number of dimensions: 2
data type in array: float64
numpy array shapre(n x m?): (3, 5)
size in bytes: 15


## 2.4 Indexing NumPy Array

In [63]:
np_arr = np.random.randint(1,10,[3,5])
np_arr

array([[6, 1, 8, 3, 1],
       [5, 8, 3, 1, 2],
       [1, 5, 2, 8, 9]])

In [64]:
np_arr[0]

array([6, 1, 8, 3, 1])

In [67]:
# numpy supports both
print(np_arr[1][2])
print(np_arr[1,2])

3
3
