# NumPy Basics

## Why Do we need NumPy?

In [2]:
nums = [1,2,3,4,5] # 1D Array (Matrix)
print(type(nums)) # type of nums
print(type(nums[0])) # type of elements in nums

<class 'list'>
<class 'int'>


Suppose you want to create a 2D matrix...

In [3]:
nums2D = [[1,2,3],[4,5,6]]
print(nums2D[0][0]) # 1
print(nums2D[0][1]) # 2
print(nums2D[0][2]) # 3
print(nums2D[1][0]) # 4
print(nums2D[1][1]) # 5
print(nums2D[1][2]) # 6

1
2
3
4
5
6


### We use NumPy to:
1. Create n-Dimensinoal Arrays (Matrices)

## 2. Getting Started with NumPy

In [4]:
# install numpy module to device
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np # import numpy module, and give alias called "np"

### 2.1 Creating Numpy Array

There are numerous Ways to Create NumPy Arrays

In [6]:
print("1.", np.array([1,4,2,5,3])) # numpy array with 5 integers in it.

print("2.", np.array([1,2,3,4], dtype="float")) # 1,2,3,4 will be upcasted to "dtype" if possible

"""
1. There are three numbers "i" can be => 2, 4, 6
2. range(i, i+3) will result in range of list with 3 numbers,
    - suppose, i = 2, range(2, 2+3) = [2,3,4]
    - suppose, i = 4, range(4, 4+3) = [4,5,6]
    - suppose, i = 6, range(6, 6+3) = [6,7,8]
"""
print("3.\n", np.array([range(i, i+3) for i in [2,4,6]]))

print("4. NumPy Array full of 0s\n", np.zeros(10, dtype="int"))

print("5. NumPy Array full of 0s\n", np.zeros([5,10], dtype="int"))

1. [1 4 2 5 3]
2. [1. 2. 3. 4.]
3.
 [[2 3 4]
 [4 5 6]
 [6 7 8]]
4. NumPy Array full of 0s
 [0 0 0 0 0 0 0 0 0 0]
5. NumPy Array full of 0s
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [7]:
print("6.NumPy Array Full of 1s\n", np.ones(10, dtype="int"))

print("7.NumPy Array Full of 1s\n", np.ones([5,10], dtype="int"))

print("8. NumPy Array Full of certain number\n", np.full([3,5], 3.14))

print("9. NumPy Arange function\n", np.arange(0, 20))
print(np.arange(0, 20, 2)) # np.arange(start, stop, step), very similar to range(start, stop, step)
print(np.arange(0, 20, 4))
print(np.arange(0, 20, 10))

print("10. NumPy Array with Line spaced\n", np.linspace(0,1,5))

print("11. NumPy Array with Random Integers\n", np.random.randint(0,10, [3,3]))
print("12. NumPy Array with Random Numbers between 0-1\n", np.random.random([3,3]))

6.NumPy Array Full of 1s
 [1 1 1 1 1 1 1 1 1 1]
7.NumPy Array Full of 1s
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
8. NumPy Array Full of certain number
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
9. NumPy Arange function
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  4  8 12 16]
[ 0 10]
10. NumPy Array with Line spaced
 [0.   0.25 0.5  0.75 1.  ]
11. NumPy Array with Random Integers
 [[2 9 1]
 [5 0 3]
 [6 8 8]]
12. NumPy Array with Random Numbers between 0-1
 [[0.23017174 0.70714895 0.04369309]
 [0.39677584 0.52696972 0.9863646 ]
 [0.56438928 0.59599227 0.46542521]]


## 2.2 NumPy Array vs. Python List

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will **Upcast** if possible.

In [8]:
print([1,2,3,4,3.14])
print(np.array([1,2,3,4,3.14])) # 1, 2, 3, 4 => 1.0, 2.0, 3.0, 4.0 (Upcasting Integer to Float)

[1, 2, 3, 4, 3.14]
[1.   2.   3.   4.   3.14]


## 2.3 NumPy Array Attributes

In [9]:
np_arr = np.full([3,5], 7.5)
print("number of dimensions:", np_arr.ndim)
print("data type in array:", np_arr.dtype)
print("numpy array shapre(n x m?):", np_arr.shape)
print("size in bytes:", np_arr.size)

number of dimensions: 2
data type in array: float64
numpy array shapre(n x m?): (3, 5)
size in bytes: 15


## 2.4 Indexing NumPy Array

In [10]:
np_arr = np.random.randint(1,10,[3,5])
np_arr

array([[5, 4, 4, 3, 3],
       [8, 3, 6, 3, 8],
       [6, 4, 9, 9, 7]])

In [11]:
np_arr[0]

array([5, 4, 4, 3, 3])

In [12]:
# numpy supports both
print(np_arr[1][2])
print(np_arr[1,2])

6
6


## 2.5 NumPy Array Slicing

### 2.5.1 String Slicing / List Slicing Recap

In [26]:
name="Ryan" # "Ryan" => ["R", "y", "a", "n"]
print(name[1:3]) # Grab the letter at index = 1 (inclusive), and then take all letters to index = 3 (exclusive)

nums = [10, 50, 14, 7, 2, 5]
print(nums[2:6]) # Grab the elements at index = 2 (inclusive), and then take all elements to index = 6 (exclusive)
print(nums[2:6:2]) # Grab the same as above, but jump 2 steps every time

ya
[14, 7, 2, 5]
[14, 2]


### 2.5.2 Slicing in NumPy Array

In [28]:
arr=np.array([
  [12,5,2,4],
  [7,6,8,8],
  [1,6,7,7]
])
arr

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [32]:
# How to slice [12, 5, 2]
## 1. slice out [12,5,2,4] from arr
arr_first_row = arr[0]
## 2. slice out [12,5,2] from 1
x1 = arr_first_row[:3]

# or in one single line
x2 = arr[0][:3]
print(x1)
print(x2)

[12  5  2]
[12  5  2]


In [36]:
# How to slice [[12,5],[7,6]]
## slice out first 2 elements from the first and second rows
x3 = arr[:2,:3]
print(x3)

[[12  5  2]
 [ 7  6  8]]


In [46]:
# How to reverse the array
revered_arr = arr[::-1, ::-1] # this is equivalent to arr[-1:-4:-1, -1:-5:-1], using step -1 (going reverse) from end to start
print("arr\n", arr)
print("revered_arr\n", revered_arr)

arr
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
revered_arr
 [[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


### 2.5.2 Exercises

In [ ]:
# 1. Create a numpy array with any number you like, but in dimension of 6x5


In [37]:
# 2. slice out 3 elements from first 4 rows, resulted sliced array should have a dimension of 4x3

In [38]:
# 3. slice out every elements that are even number index from every odd rows, resulted sliced array should have a dimension of 3x2

In [ ]:
# 4. slice out last 2 element from two last rows in reversed order 